description: "All info about me, my projects, skills, education, experiences and certifications."
google_analytics: UA-140879800-1
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-seo-tag
relative_links:
  collections: true
  enabled: true
# theme: jekyll-theme-hacker
remote_theme: pmarsceill/just-the-docs
search_enabled: false
aux_links:
  "gbkel-about on GitHub":
    - "//github.com/guilhermebkel/gbkel-about"
ga_tracking: UA-140879800-1
exclude:
  - README.md
footer_content: "A lot of info about <a href=\"https://github.com/guilhermebkel\">Guilherme Mota Bromonschenkel Lima.</a>"
color_scheme: dark
