description: "All info about me, my projects, skills, education, experiences and certifications."
google_analytics: UA-140879800-1
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-remote-theme
  - jekyll-seo-tag
relative_links:
  collections: true
  enabled: true
# theme: jekyll-theme-hacker
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
  "Life Long Road on GitHub":
    - "//github.com/guilhermebkel/life-long-road"
ga_tracking: UA-140879800-1
exclude:
  - README.md
